# Generated by Django 3.0.2 on 2020-01-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='label',
            new_name='title',
        ),
    ]
