# Generated by Django 3.0.2 on 2020-01-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Profiles", "0002_auto_20200118_2007"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("Α", "Άντρας"), ("Γ", "Γυναίκα")], max_length=1
            ),
        ),
    ]
