FROM arm64v8/ubuntu
ENV PYTHONUNBUFFERED=1

WORKDIR /chaoticbook
COPY . /chaoticbook/

SHELL ["/bin/bash", "-c"]

RUN apt update && apt install python3.9 -y
RUN apt install python3-pip -y

RUN echo 'alias python="python3.9"' >> ~/.bashrc
RUN source ~/.bashrc

RUN python -m pip install --upgrade pip
RUN python -m pip install -r requirements.txt
