name: Django Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build postgres
        run: |
          make build-postgres
          docker save -o postgres.tar postgres

      - name: Build django
        run: |
          make build-django
          docker save -o django.tar django

      - name: Upload postgres
        uses: actions/upload-artifact@v2
        with:
          name: postgres
          path: ./postgres.tar

      - name: Upload django
        uses: actions/upload-artifact@v2
        with:
          name: django
          path: ./django.tar

  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Download postgres
        uses: actions/download-artifact@v2
        with:
          name: postgres

      - name: Download django
        uses: actions/download-artifact@v2
        with:
          name: django

      - name: Load images
        run: |
          docker load -i postgres.tar
          docker load -i django.tar

      - name: Check formating
        run: make check

      - name: Run Tests
        run: make unit-tests

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Download postgres
        uses: actions/download-artifact@v2
        with:
          name: postgres
          path: ./postgres.tar

      - name: Download django
        uses: actions/download-artifact@v2
        with:
          name: django
          path: ./django.tar
